[package]
# name = "{{project-name}}"
# version = "0.1.0"
# authors = ["{{authors}}"]
name = "foo"
version = "0.1.0"
authors = ["bar"]

[dependencies]
cotton = { git = "https://github.com/jpastuszek/cotton.git" }
structopt = "0.2.12"
log = "0.4.5"
